/**
 * Cross-implementation parity test: Python -> TypeScript
 *
 * Reads test vectors generated by Python (python/tests/generate_py_vectors.py)
 * and verifies that the TypeScript crypto implementation produces identical
 * outputs for all derived values, and can decrypt Python-encrypted data.
 *
 * Run:
 *   cd tests/parity && npx tsx cross-impl-test.ts
 *   -- or from repo root --
 *   node --experimental-strip-types tests/parity/cross-impl-test.ts
 */

import { readFileSync } from 'fs';
import { join, dirname } from 'path';
import { fileURLToPath } from 'url';

import {
  deriveKeys,
  deriveLshSeed,
  computeAuthKeyHash,
  decrypt as tsDecrypt,
  generateBlindIndices,
  generateContentFingerprint,
  LSHHasher,
} from './nanoclaw-adapter.ts';

import { sha256 } from '@noble/hashes/sha2.js';

const __dirname = dirname(fileURLToPath(import.meta.url));

// ---------------------------------------------------------------------------
// Types
// ---------------------------------------------------------------------------

interface PyVectors {
  mnemonic: string;
  source: string;
  derived: {
    salt_hex: string;
    auth_key_hex: string;
    encryption_key_hex: string;
    dedup_key_hex: string;
    auth_key_hash_hex: string;
    lsh_seed_hex: string;
  };
  encryption: {
    plaintext: string;
    encrypted_base64: string;
  };
  blind_indices: {
    input_text: string;
    expected: string[];
  };
  content_fingerprint: {
    input_text: string;
    expected_hex: string;
  };
  lsh: {
    embedding_seed: number;
    embedding_dims: number;
    n_tables: number;
    n_bits: number;
    expected_buckets: string[];
  };
}

// ---------------------------------------------------------------------------
// Test harness
// ---------------------------------------------------------------------------

let passed = 0;
let failed = 0;

function assert(condition: boolean, msg: string): void {
  if (condition) {
    passed++;
    console.log(`  PASS  ${msg}`);
  } else {
    failed++;
    console.error(`  FAIL  ${msg}`);
  }
}

// ---------------------------------------------------------------------------
// Deterministic embedding generator (must match Python's make_embedding)
// ---------------------------------------------------------------------------

function makeEmbedding(seed: number, dims: number): number[] {
  const vec: number[] = new Array(dims);
  let hash = sha256(Buffer.from(`embedding_${seed}`, 'utf8'));
  let offset = 0;
  const view = new DataView(new ArrayBuffer(4));

  for (let i = 0; i < dims; i++) {
    if (offset + 4 > hash.length) {
      hash = sha256(hash);
      offset = 0;
    }
    view.setUint8(0, hash[offset]);
    view.setUint8(1, hash[offset + 1]);
    view.setUint8(2, hash[offset + 2]);
    view.setUint8(3, hash[offset + 3]);
    vec[i] = (view.getUint32(0, true) / 0xFFFFFFFF) * 2 - 1;
    offset += 4;
  }

  let norm = 0;
  for (let i = 0; i < dims; i++) norm += vec[i] * vec[i];
  norm = Math.sqrt(norm);
  for (let i = 0; i < dims; i++) vec[i] /= norm;

  return vec;
}

// ---------------------------------------------------------------------------
// Main
// ---------------------------------------------------------------------------

async function main(): Promise<void> {
  const vectorsPath = join(__dirname, '../../python/tests/fixtures/py_vectors.json');
  const vectors: PyVectors = JSON.parse(readFileSync(vectorsPath, 'utf-8'));

  console.log(`\nCross-implementation parity tests (Python -> TypeScript)\n`);
  console.log(`Source: ${vectors.source}`);
  console.log(`Mnemonic: ${vectors.mnemonic.slice(0, 30)}...\n`);

  // =========================================================================
  // 1. Key derivation parity
  // =========================================================================
  console.log('Key derivation:');
  const tsKeys = deriveKeys(vectors.mnemonic);
  const tsSalt = tsKeys.salt.toString('hex');
  const tsAuthKey = tsKeys.authKey.toString('hex');
  const tsEncKey = tsKeys.encryptionKey.toString('hex');
  const tsDedupKey = tsKeys.dedupKey.toString('hex');

  assert(tsSalt === vectors.derived.salt_hex, 'salt matches');
  assert(tsAuthKey === vectors.derived.auth_key_hex, 'auth_key matches');
  assert(tsEncKey === vectors.derived.encryption_key_hex, 'encryption_key matches');
  assert(tsDedupKey === vectors.derived.dedup_key_hex, 'dedup_key matches');

  const tsAuthHash = computeAuthKeyHash(tsKeys.authKey);
  assert(tsAuthHash === vectors.derived.auth_key_hash_hex, 'auth_key_hash matches');

  const tsLshSeed = deriveLshSeed(vectors.mnemonic, tsKeys.salt);
  assert(
    Buffer.from(tsLshSeed).toString('hex') === vectors.derived.lsh_seed_hex,
    'lsh_seed matches',
  );

  // =========================================================================
  // 2. Cross-decryption: TypeScript decrypts Python-encrypted data
  // =========================================================================
  console.log('\nCross-decryption:');
  const decrypted = tsDecrypt(vectors.encryption.encrypted_base64, tsKeys.encryptionKey);
  assert(decrypted === vectors.encryption.plaintext, 'TS decrypts Python ciphertext');

  // =========================================================================
  // 3. Blind indices parity
  // =========================================================================
  // NOTE: TypeScript uses Porter1 stemmer, Python uses Snowball (Porter2).
  // Python may produce additional stem hashes. We verify that all TS indices
  // appear in the Python set (TS is a subset of Python).
  console.log('\nBlind indices:');
  const tsIndices = generateBlindIndices(vectors.blind_indices.input_text);
  const pyIndices = vectors.blind_indices.expected;
  const pySet = new Set(pyIndices);

  assert(tsIndices.length > 0, `TS produces indices (${tsIndices.length})`);
  assert(pyIndices.length >= tsIndices.length, `Python has >= TS count (${pyIndices.length} >= ${tsIndices.length})`);

  let allTsInPy = true;
  for (const idx of tsIndices) {
    if (!pySet.has(idx)) {
      allTsInPy = false;
      console.error(`    TS index not in Python: ${idx}`);
    }
  }
  assert(allTsInPy, `all TS blind indices present in Python set`);

  // =========================================================================
  // 4. Content fingerprint parity
  // =========================================================================
  console.log('\nContent fingerprint:');
  const tsFp = generateContentFingerprint(
    vectors.content_fingerprint.input_text,
    tsKeys.dedupKey,
  );
  assert(tsFp === vectors.content_fingerprint.expected_hex, 'content fingerprint matches');

  // =========================================================================
  // 5. LSH bucket parity
  // =========================================================================
  console.log('\nLSH buckets:');
  const hasher = new LSHHasher(
    tsLshSeed,
    vectors.lsh.embedding_dims,
    vectors.lsh.n_tables,
    vectors.lsh.n_bits,
  );

  const embedding = makeEmbedding(vectors.lsh.embedding_seed, vectors.lsh.embedding_dims);
  const tsBuckets = hasher.hash(embedding);
  const pyBuckets = vectors.lsh.expected_buckets;

  assert(tsBuckets.length === pyBuckets.length, `same bucket count (${tsBuckets.length})`);

  let bucketsMatch = true;
  for (let i = 0; i < tsBuckets.length; i++) {
    if (tsBuckets[i] !== pyBuckets[i]) {
      bucketsMatch = false;
      console.error(`    mismatch at table ${i}: TS=${tsBuckets[i]} PY=${pyBuckets[i]}`);
    }
  }
  assert(bucketsMatch, `all ${tsBuckets.length} LSH bucket hashes match`);

  // =========================================================================
  // Summary
  // =========================================================================
  console.log(`\n${'='.repeat(50)}`);
  console.log(`Results: ${passed} passed, ${failed} failed`);
  if (failed > 0) {
    process.exit(1);
  }
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
