/**
 * `derived-bundle-v1` cross-language parity test (TypeScript / WASM side).
 *
 * Loads `fixtures/derived-bundle-v1.json` (generated by
 * `fixtures/generate-derived-bundle-v1.ts`) and asserts:
 *
 *   1. `deriveBundleFromMnemonic(...)` is byte-equal to the fixture's
 *      `expected` subset (vault, signing, account, provisioned_by) —
 *      `provisioned_at` is deliberately excluded (wall-clock, informational
 *      only — see the generator's header comment).
 *   2. `parseBundleV1` round-trips the derived bundle without loss.
 *   3. The derived JSON's field order is stable
 *      (`JSON.stringify(JSON.parse(json)) === json`), proving
 *      `bundle_to_json` serialises a fixed-order struct rather than a map.
 *   4. `validateBundleV1` accepts a valid bundle and rejects a tampered one.
 *
 * Run (build the flat WASM pkg first):
 *   cd rust/totalreclaw-core && wasm-pack build --target nodejs --out-dir pkg --features wasm
 *   cd tests/parity && node --experimental-strip-types derived-bundle-parity.test.ts
 *   -- or --
 *   cd tests/parity && npx tsx derived-bundle-parity.test.ts
 */

import { readFileSync } from 'fs';
import { dirname, resolve } from 'path';
import { fileURLToPath } from 'url';
import { createRequire } from 'module';

const __dirname = dirname(fileURLToPath(import.meta.url));
const require = createRequire(import.meta.url);

const wasmPath = resolve(__dirname, '..', '..', 'rust', 'totalreclaw-core', 'pkg', 'totalreclaw_core.js');
const wasm = require(wasmPath) as {
  deriveBundleFromMnemonic: (
    mnemonic: string,
    chainId: bigint,
    provisionedBy: string,
    smartAccount: string,
  ) => string;
  parseBundleV1: (json: string) => unknown;
  validateBundleV1: (json: string) => void;
};

interface Fixture {
  inputs: {
    mnemonic: string;
    chain_id: number;
    provisioned_by: string;
    smart_account: string;
  };
  expected: {
    vault: Record<string, string>;
    signing: Record<string, string>;
    account: { smart_account: string; chain_id: number };
    provisioned_by: string;
  };
}

const fixture: Fixture = JSON.parse(
  readFileSync(resolve(__dirname, 'fixtures', 'derived-bundle-v1.json'), 'utf8'),
);

let passed = 0;
let failed = 0;

function assertDeepEqual(actual: unknown, expected: unknown, label: string): void {
  const a = JSON.stringify(actual);
  const e = JSON.stringify(expected);
  if (a === e) {
    passed++;
  } else {
    failed++;
    console.error(`FAIL [${label}]\n  actual:   ${a}\n  expected: ${e}`);
  }
}

function assertTrue(condition: boolean, label: string): void {
  if (condition) {
    passed++;
  } else {
    failed++;
    console.error(`FAIL [${label}]`);
  }
}

function assertThrows(fn: () => void, label: string): void {
  try {
    fn();
    failed++;
    console.error(`FAIL [${label}] — expected a throw, none occurred`);
  } catch {
    passed++;
  }
}

// -- 1. Byte-equality against the fixture ------------------------------------

const json = wasm.deriveBundleFromMnemonic(
  fixture.inputs.mnemonic,
  BigInt(fixture.inputs.chain_id),
  fixture.inputs.provisioned_by,
  fixture.inputs.smart_account,
);
const derived = JSON.parse(json);

assertDeepEqual(derived.vault, fixture.expected.vault, 'vault matches fixture');
assertDeepEqual(derived.signing, fixture.expected.signing, 'signing matches fixture');
assertDeepEqual(derived.account, fixture.expected.account, 'account matches fixture');
assertDeepEqual(derived.provisioned_by, fixture.expected.provisioned_by, 'provisioned_by matches fixture');
assertTrue(
  typeof derived.provisioned_at === 'string' && !Number.isNaN(Date.parse(derived.provisioned_at)),
  'provisioned_at is a valid timestamp (not asserted verbatim)',
);
assertTrue(derived.version === 2, 'version == 2');
assertTrue(derived.schema === 'derived-bundle-v1', 'schema == derived-bundle-v1');

// -- 2. parseBundleV1 round-trips without loss --------------------------------

const parsed = wasm.parseBundleV1(json) as {
  vault: Record<string, string>;
  signing: Record<string, string>;
  account: { smart_account: string; chain_id: number };
  provisioned_at: string;
  provisioned_by: string;
};
assertDeepEqual(parsed.vault, fixture.expected.vault, 'parseBundleV1: vault matches fixture');
assertDeepEqual(parsed.signing, fixture.expected.signing, 'parseBundleV1: signing matches fixture');
assertDeepEqual(parsed.account, fixture.expected.account, 'parseBundleV1: account matches fixture');

// -- 3. Field order is stable (fixed-order struct, not a map) ---------------

assertTrue(JSON.stringify(JSON.parse(json)) === json, 'derived JSON re-stringifies byte-identically (no whitespace in source — sanity: compares parsed-then-restringified against the compact original)');

const keys = Object.keys(derived);
assertDeepEqual(
  keys,
  ['version', 'schema', 'vault', 'signing', 'account', 'provisioned_at', 'provisioned_by'],
  'top-level field order matches derived-bundle-v1.md §4.1',
);
const vaultKeys = Object.keys(derived.vault);
assertDeepEqual(
  vaultKeys,
  ['encryption_key', 'dedup_key', 'auth_key', 'lsh_seed'],
  'vault field order matches derived-bundle-v1.md §4.1',
);

// -- 4. validateBundleV1 accepts valid, rejects tampered ---------------------

wasm.validateBundleV1(json); // must not throw
passed++;

const tampered = json.replace(fixture.expected.signing.address, '0x000000000000000000000000000000000000dd');
assertThrows(() => wasm.validateBundleV1(tampered), 'validateBundleV1 rejects address/private_key mismatch');

const wrongVersion = json.replace('"version":2', '"version":3');
assertThrows(() => wasm.validateBundleV1(wrongVersion), 'validateBundleV1 rejects wrong version');

// -- 5. No root material in the serialised bundle -----------------------------

assertTrue(!json.includes('abandon'), 'serialised bundle never contains the mnemonic');

// -----------------------------------------------------------------------------

console.log(`\n========================================`);
console.log(`derived-bundle-v1 TS/WASM parity: ${passed}/${passed + failed} assertions passed`);
console.log(`========================================`);
if (failed > 0) {
  console.error(`FAIL: ${failed} assertion(s) failed`);
  process.exit(1);
}
console.log('PASS: all derived-bundle-v1 vectors match between Rust (canonical) and WASM');
