/**
 * Cross-language Crypto Test Fixture Generator
 *
 * Generates a JSON file with known inputs -> expected outputs from the
 * canonical TypeScript crypto implementation (MCP server). The Python
 * client uses these fixtures to verify byte-for-byte parity.
 *
 * Usage (from repo root):
 *   node --experimental-strip-types tests/parity/generate-fixtures.ts > python/tests/fixtures/crypto_vectors.json
 */

import {
  deriveKeysFromMnemonic,
  computeAuthKeyHash,
  deriveLshSeed,
  encrypt,
  decrypt,
  generateBlindIndices,
  generateContentFingerprint,
} from '../../mcp/src/subgraph/crypto.ts';

import { LSHHasher } from '../../mcp/src/subgraph/lsh.ts';
import { sha256 } from '@noble/hashes/sha2.js';

// ---------------------------------------------------------------------------
// Constants
// ---------------------------------------------------------------------------

const TEST_MNEMONIC =
  'abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon about';

const TEST_PLAINTEXT = 'The user prefers dark mode and uses Vim keybindings.';
const BLIND_INDEX_TEXT = 'Alice likes distributed systems and Rust programming';
const EMBEDDING_SEED = 42;
const EMBEDDING_DIMS = 1024;

// ---------------------------------------------------------------------------
// Deterministic embedding generator (reproducible across languages)
// ---------------------------------------------------------------------------

/**
 * Generate a deterministic unit-norm embedding from a seed.
 *
 * Uses SHA-256 in counter mode to produce uniform random bytes, converts to
 * floats in [-1, 1], then L2-normalizes. The exact algorithm must be
 * re-implemented identically in Python for the fixtures to be useful.
 */
function makeEmbedding(seed: number, dims: number): number[] {
  const vec: number[] = new Array(dims);
  let hash = sha256(Buffer.from(`embedding_${seed}`, 'utf8'));
  let offset = 0;
  const view = new DataView(new ArrayBuffer(4));

  for (let i = 0; i < dims; i++) {
    if (offset + 4 > hash.length) {
      hash = sha256(hash);
      offset = 0;
    }
    view.setUint8(0, hash[offset]);
    view.setUint8(1, hash[offset + 1]);
    view.setUint8(2, hash[offset + 2]);
    view.setUint8(3, hash[offset + 3]);
    vec[i] = (view.getUint32(0, true) / 0xFFFFFFFF) * 2 - 1;
    offset += 4;
  }

  let norm = 0;
  for (let i = 0; i < dims; i++) norm += vec[i] * vec[i];
  norm = Math.sqrt(norm);
  for (let i = 0; i < dims; i++) vec[i] /= norm;

  return vec;
}

// ---------------------------------------------------------------------------
// Main
// ---------------------------------------------------------------------------

function main(): void {
  // 1. Key derivation
  const { authKey, encryptionKey, dedupKey, salt } =
    deriveKeysFromMnemonic(TEST_MNEMONIC);

  const authKeyHash = computeAuthKeyHash(authKey);
  const lshSeed = deriveLshSeed(TEST_MNEMONIC, salt);

  // 2. Encryption (deterministic decrypt test -- we encrypt and record the
  //    ciphertext so the Python side can decrypt it)
  const encryptedBase64 = encrypt(TEST_PLAINTEXT, encryptionKey);

  // Verify round-trip
  const decrypted = decrypt(encryptedBase64, encryptionKey);
  if (decrypted !== TEST_PLAINTEXT) {
    throw new Error('Encryption round-trip failed');
  }

  // 3. Blind indices
  const blindIndices = generateBlindIndices(BLIND_INDEX_TEXT);

  // 4. Content fingerprint
  const contentFingerprint = generateContentFingerprint(
    TEST_PLAINTEXT,
    dedupKey,
  );

  // 5. LSH buckets
  const embedding = makeEmbedding(EMBEDDING_SEED, EMBEDDING_DIMS);
  const lshHasher = new LSHHasher(lshSeed, EMBEDDING_DIMS);
  const lshBuckets = lshHasher.hash(embedding);

  // 6. Assemble fixture
  const fixture = {
    _comment:
      'Auto-generated by tests/parity/generate-fixtures.ts — DO NOT EDIT',
    _generated_at: new Date().toISOString(),

    mnemonic: TEST_MNEMONIC,

    derived: {
      salt_hex: salt.toString('hex'),
      auth_key_hex: authKey.toString('hex'),
      encryption_key_hex: encryptionKey.toString('hex'),
      dedup_key_hex: dedupKey.toString('hex'),
      auth_key_hash_hex: authKeyHash,
      lsh_seed_hex: Buffer.from(lshSeed).toString('hex'),
    },

    encryption: {
      plaintext: TEST_PLAINTEXT,
      encrypted_base64: encryptedBase64,
    },

    blind_indices: {
      input_text: BLIND_INDEX_TEXT,
      expected: blindIndices,
    },

    content_fingerprint: {
      input_text: TEST_PLAINTEXT,
      expected_hex: contentFingerprint,
    },

    lsh: {
      embedding_seed: EMBEDDING_SEED,
      embedding_dims: EMBEDDING_DIMS,
      n_tables: 20,
      n_bits: 32,
      embedding: embedding,
      expected_buckets: lshBuckets,
    },
  };

  // Output JSON to stdout
  process.stdout.write(JSON.stringify(fixture, null, 2) + '\n');
}

main();
