/**
 * KG Phase 1 cross-language parity test (TypeScript / WASM side).
 *
 * Loads `kg_phase1_vectors.json` (generated by the Rust example
 * `cargo run --example generate_kg_fixtures --release`) and asserts that
 * the WASM bindings produce byte-identical output for every vector.
 *
 * Run:
 *   cd tests/parity && node --experimental-strip-types kg-phase1-parity.test.ts
 *   -- or --
 *   cd tests/parity && npx tsx kg-phase1-parity.test.ts
 */

import { readFileSync } from 'fs';
import { join, dirname, resolve } from 'path';
import { fileURLToPath } from 'url';
import { createRequire } from 'module';

const __dirname = dirname(fileURLToPath(import.meta.url));
const require = createRequire(import.meta.url);

// Load the WASM bindings (CJS module produced by wasm-pack).
const wasmPath = resolve(
  __dirname,
  '..',
  '..',
  'rust',
  'totalreclaw-core',
  'pkg',
  'totalreclaw_core.js'
);
const wasm = require(wasmPath) as {
  normalizeEntityName: (name: string) => string;
  deterministicEntityId: (name: string) => string;
  parseClaimOrLegacy: (decrypted: string) => string;
  canonicalizeClaim: (claimJson: string) => string;
  buildTemplateDigest: (claimsJson: string, nowUnix: bigint) => string;
  buildDigestPrompt: (claimsJson: string) => string;
  parseDigestResponse: (raw: string) => string;
  assembleDigestFromLlm: (
    parsedJson: string,
    claimsJson: string,
    nowUnix: bigint
  ) => string;
};

// ----------------------------------------------------------------------------
// Fixture types
// ----------------------------------------------------------------------------

interface EntityVector {
  input: string;
  normalized: string;
  entity_id: string;
}
interface CanonicalVector {
  input: string;
  canonical: string;
}
interface LegacyVector {
  input: string;
  output: string;
}
interface TemplateDigestVector {
  input_claims: string;
  now_unix_seconds: number;
  digest: string;
}
interface DigestPromptVector {
  input_claims: string;
  prompt: string;
}
interface ParseDigestVector {
  input: string;
  output: string;
}
interface AssembleVector {
  parsed_response: string;
  input_claims: string;
  now_unix_seconds: number;
  digest: string;
}

interface Fixtures {
  meta: { version: number; now_unix_seconds: number; description: string };
  entity_normalization: EntityVector[];
  claim_canonicalization: CanonicalVector[];
  legacy_parser: LegacyVector[];
  template_digest: TemplateDigestVector[];
  digest_prompt: DigestPromptVector[];
  parse_digest_response: ParseDigestVector[];
  assemble_digest_from_llm: AssembleVector[];
}

// ----------------------------------------------------------------------------
// Test runner
// ----------------------------------------------------------------------------

const fixturePath = join(__dirname, 'kg_phase1_vectors.json');
const fixtures = JSON.parse(readFileSync(fixturePath, 'utf8')) as Fixtures;

interface CategoryResult {
  name: string;
  passed: number;
  failed: number;
  failures: string[];
}

const results: CategoryResult[] = [];

function runCategory(
  name: string,
  _vectorCount: number,
  body: (record: (ok: boolean, label: string, expected?: unknown, actual?: unknown) => void) => void
): CategoryResult {
  const r: CategoryResult = { name, passed: 0, failed: 0, failures: [] };
  const record = (
    ok: boolean,
    label: string,
    expected?: unknown,
    actual?: unknown
  ) => {
    if (ok) {
      r.passed += 1;
    } else {
      r.failed += 1;
      r.failures.push(
        `  - ${label}\n    expected: ${JSON.stringify(expected)}\n    actual:   ${JSON.stringify(actual)}`
      );
    }
  };
  body(record);
  results.push(r);
  const total = r.passed + r.failed;
  console.log(
    `[${name}] ${r.passed}/${total} assertions passed${r.failed ? ` (${r.failed} FAILED)` : ''}`
  );
  if (r.failed) {
    for (const f of r.failures) console.error(f);
  }
  return r;
}

// ---- Category 1: entity normalization ----
runCategory('entity_normalization', fixtures.entity_normalization.length, (record) => {
  for (const v of fixtures.entity_normalization) {
    const norm = wasm.normalizeEntityName(v.input);
    record(
      norm === v.normalized,
      `normalizeEntityName(${JSON.stringify(v.input)})`,
      v.normalized,
      norm
    );
    const id = wasm.deterministicEntityId(v.input);
    record(
      id === v.entity_id,
      `deterministicEntityId(${JSON.stringify(v.input)})`,
      v.entity_id,
      id
    );
  }
});

// ---- Category 2: claim canonicalization ----
runCategory(
  'claim_canonicalization',
  fixtures.claim_canonicalization.length,
  (record) => {
    for (const v of fixtures.claim_canonicalization) {
      const out = wasm.canonicalizeClaim(v.input);
      record(
        out === v.canonical,
        `canonicalizeClaim(${v.input})`,
        v.canonical,
        out
      );
    }
  }
);

// ---- Category 3: legacy parser ----
runCategory('legacy_parser', fixtures.legacy_parser.length, (record) => {
  for (const v of fixtures.legacy_parser) {
    const out = wasm.parseClaimOrLegacy(v.input);
    record(
      out === v.output,
      `parseClaimOrLegacy(${JSON.stringify(v.input)})`,
      v.output,
      out
    );
  }
});

// ---- Category 4: template digest ----
runCategory('template_digest', fixtures.template_digest.length, (record) => {
  for (const [i, v] of fixtures.template_digest.entries()) {
    const out = wasm.buildTemplateDigest(v.input_claims, BigInt(v.now_unix_seconds));
    record(
      out === v.digest,
      `buildTemplateDigest[#${i}] (${v.input_claims.length} bytes input)`,
      v.digest,
      out
    );
  }
});

// ---- Category 5: build digest prompt ----
runCategory('digest_prompt', fixtures.digest_prompt.length, (record) => {
  for (const [i, v] of fixtures.digest_prompt.entries()) {
    const out = wasm.buildDigestPrompt(v.input_claims);
    record(out === v.prompt, `buildDigestPrompt[#${i}]`, v.prompt, out);
  }
});

// ---- Category 6: parse digest response ----
runCategory(
  'parse_digest_response',
  fixtures.parse_digest_response.length,
  (record) => {
    for (const [i, v] of fixtures.parse_digest_response.entries()) {
      const out = wasm.parseDigestResponse(v.input);
      record(out === v.output, `parseDigestResponse[#${i}]`, v.output, out);
    }
  }
);

// ---- Category 7: assemble digest from llm ----
runCategory(
  'assemble_digest_from_llm',
  fixtures.assemble_digest_from_llm.length,
  (record) => {
    for (const [i, v] of fixtures.assemble_digest_from_llm.entries()) {
      const out = wasm.assembleDigestFromLlm(
        v.parsed_response,
        v.input_claims,
        BigInt(v.now_unix_seconds)
      );
      record(out === v.digest, `assembleDigestFromLlm[#${i}]`, v.digest, out);
    }
  }
);

// ----------------------------------------------------------------------------
// Summary
// ----------------------------------------------------------------------------

const totalPassed = results.reduce((s, r) => s + r.passed, 0);
const totalFailed = results.reduce((s, r) => s + r.failed, 0);
const totalVectors = totalPassed + totalFailed;

console.log('');
console.log('========================================');
console.log(`KG Phase 1 TS/WASM parity: ${totalPassed}/${totalVectors} assertions passed`);
console.log('========================================');

if (totalFailed > 0) {
  console.error(`FAIL: ${totalFailed} parity assertion(s) failed`);
  process.exit(1);
}
console.log('PASS: all KG Phase 1 vectors match between Rust (canonical) and WASM');
process.exit(0);
