"""KG Phase 1 cross-language parity test (Python / PyO3 side).

Loads ``kg_phase1_vectors.json`` (generated by the Rust example
``cargo run --example generate_kg_fixtures --release``) and asserts that
the PyO3 bindings in ``totalreclaw_core`` produce byte-identical output for
every vector.

Run::

    /Users/pdiogo/Documents/code/totalreclaw/python/.venv/bin/python3 \
        tests/parity/test_kg_phase1_parity.py

The script exits with status 0 on PASS and 1 on FAIL.
"""

from __future__ import annotations

import json
import sys
from pathlib import Path
from typing import Any, Callable, List

import totalreclaw_core as core


HERE = Path(__file__).resolve().parent
FIXTURE_PATH = HERE / "kg_phase1_vectors.json"


class CategoryResult:
    def __init__(self, name: str) -> None:
        self.name = name
        self.passed = 0
        self.failed = 0
        self.failures: List[str] = []

    def record(
        self,
        ok: bool,
        label: str,
        expected: Any = None,
        actual: Any = None,
    ) -> None:
        if ok:
            self.passed += 1
        else:
            self.failed += 1
            self.failures.append(
                f"  - {label}\n    expected: {expected!r}\n    actual:   {actual!r}"
            )

    @property
    def total(self) -> int:
        return self.passed + self.failed


def run_category(
    name: str, body: Callable[[CategoryResult], None]
) -> CategoryResult:
    r = CategoryResult(name)
    body(r)
    suffix = f" ({r.failed} FAILED)" if r.failed else ""
    print(f"[{name}] {r.passed}/{r.total} assertions passed{suffix}")
    if r.failed:
        for line in r.failures:
            print(line, file=sys.stderr)
    return r


def main() -> int:
    if not FIXTURE_PATH.exists():
        print(
            f"FAIL: fixture file not found: {FIXTURE_PATH}\n"
            "Generate it first with: cd rust/totalreclaw-core && "
            "cargo run --example generate_kg_fixtures --release",
            file=sys.stderr,
        )
        return 1

    with FIXTURE_PATH.open("r", encoding="utf-8") as f:
        fixtures = json.load(f)

    results: List[CategoryResult] = []

    # ---- Category 1: entity normalization + deterministic IDs ----
    def cat_entity(r: CategoryResult) -> None:
        for v in fixtures["entity_normalization"]:
            inp = v["input"]
            norm = core.normalize_entity_name(inp)
            r.record(
                norm == v["normalized"],
                f"normalize_entity_name({inp!r})",
                v["normalized"],
                norm,
            )
            ent_id = core.deterministic_entity_id(inp)
            r.record(
                ent_id == v["entity_id"],
                f"deterministic_entity_id({inp!r})",
                v["entity_id"],
                ent_id,
            )

    results.append(run_category("entity_normalization", cat_entity))

    # ---- Category 2: claim canonicalization ----
    def cat_canonical(r: CategoryResult) -> None:
        for v in fixtures["claim_canonicalization"]:
            out = core.canonicalize_claim(v["input"])
            r.record(
                out == v["canonical"],
                f"canonicalize_claim({v['input']})",
                v["canonical"],
                out,
            )

    results.append(run_category("claim_canonicalization", cat_canonical))

    # ---- Category 3: legacy parser ----
    def cat_legacy(r: CategoryResult) -> None:
        for v in fixtures["legacy_parser"]:
            out = core.parse_claim_or_legacy(v["input"])
            r.record(
                out == v["output"],
                f"parse_claim_or_legacy({v['input']!r})",
                v["output"],
                out,
            )

    results.append(run_category("legacy_parser", cat_legacy))

    # ---- Category 4: template digest ----
    def cat_template(r: CategoryResult) -> None:
        for i, v in enumerate(fixtures["template_digest"]):
            out = core.build_template_digest(
                v["input_claims"], int(v["now_unix_seconds"])
            )
            r.record(
                out == v["digest"],
                f"build_template_digest[#{i}] ({len(v['input_claims'])} bytes input)",
                v["digest"],
                out,
            )

    results.append(run_category("template_digest", cat_template))

    # ---- Category 5: build_digest_prompt ----
    def cat_prompt(r: CategoryResult) -> None:
        for i, v in enumerate(fixtures["digest_prompt"]):
            out = core.build_digest_prompt(v["input_claims"])
            r.record(
                out == v["prompt"],
                f"build_digest_prompt[#{i}]",
                v["prompt"],
                out,
            )

    results.append(run_category("digest_prompt", cat_prompt))

    # ---- Category 6: parse_digest_response ----
    def cat_parse(r: CategoryResult) -> None:
        for i, v in enumerate(fixtures["parse_digest_response"]):
            out = core.parse_digest_response(v["input"])
            r.record(
                out == v["output"],
                f"parse_digest_response[#{i}]",
                v["output"],
                out,
            )

    results.append(run_category("parse_digest_response", cat_parse))

    # ---- Category 7: assemble_digest_from_llm ----
    def cat_assemble(r: CategoryResult) -> None:
        for i, v in enumerate(fixtures["assemble_digest_from_llm"]):
            out = core.assemble_digest_from_llm(
                v["parsed_response"],
                v["input_claims"],
                int(v["now_unix_seconds"]),
            )
            r.record(
                out == v["digest"],
                f"assemble_digest_from_llm[#{i}]",
                v["digest"],
                out,
            )

    results.append(run_category("assemble_digest_from_llm", cat_assemble))

    # ---- Summary ----
    total_passed = sum(r.passed for r in results)
    total_failed = sum(r.failed for r in results)
    total = total_passed + total_failed

    print()
    print("=" * 40)
    print(
        f"KG Phase 1 Python/PyO3 parity: {total_passed}/{total} assertions passed"
    )
    print("=" * 40)

    if total_failed:
        print(
            f"FAIL: {total_failed} parity assertion(s) failed", file=sys.stderr
        )
        return 1

    print(
        "PASS: all KG Phase 1 vectors match between Rust (canonical) and PyO3"
    )
    return 0


if __name__ == "__main__":
    sys.exit(main())
