"""Install TotalReclaw as a Hermes MemoryProvider (Path B — issue #275).

This module drops a one-file sidecar shim at
``$HERMES_HOME/plugins/memory/totalreclaw/__init__.py`` so Hermes'
built-in memory-provider loader picks up :class:`TotalReclawMemoryProvider`
without needing an upstream API addition.

Why a sidecar
-------------
Hermes' plugin context (``ctx`` passed to ``register()``) does not
expose ``register_memory_provider`` — only tools and lifecycle hooks.
Memory providers are discovered by scanning ``plugins/memory/<name>/``
for ``MemoryProvider`` subclasses. The sidecar imports our class from
the installed ``totalreclaw`` PyPI package, so the heavy lifting stays
in the main distribution and the on-disk file is a 3-line stub.

UX
--
Activation flow handled by the agent (see ``SKILL.md``):

  1. Read current provider via :func:`read_active_provider` (config grep —
     upstream ``hermes memory status --json`` is not yet released; see
     spec §"Open questions for upstream").
  2. If ``"none"`` / ``""`` / ``"totalreclaw"``: call
     :func:`install_sidecar` + :func:`set_active_provider` silently.
  3. If another provider is active: ask the user "switch or tools-only?".
     - **switch** → :func:`install_sidecar` + :func:`set_active_provider`
       (warn that the previous provider deactivates).
     - **tools-only** → :func:`install_sidecar` only; TR tools remain
       available, hooks don't fire because TR isn't the active provider.

All operations are idempotent: rerunning on an already-installed
sidecar overwrites with the current shim content (catches package
upgrades that change the import path) without disturbing other state.
"""
from __future__ import annotations

import logging
import os
import re
from pathlib import Path
from typing import Optional

logger = logging.getLogger(__name__)

# Generated comment: keep the marker line stable so future versions can
# detect a managed sidecar and refuse to clobber a hand-edited one.
_SIDECAR_MARKER = "# managed-by: totalreclaw.hermes.install_memory_provider"

_SIDECAR_CONTENT = f"""\
{_SIDECAR_MARKER}
\"\"\"Hermes MemoryProvider sidecar for TotalReclaw.

This file is auto-generated by ``totalreclaw hermes install-memory-provider``.
It re-exports :class:`TotalReclawMemoryProvider` from the installed
``totalreclaw`` PyPI package so Hermes' ``plugins/memory/<name>/``
loader can discover it.

Do not edit by hand — re-run the install command on package upgrade.
\"\"\"
from totalreclaw.hermes.memory_provider import TotalReclawMemoryProvider

__all__ = ["TotalReclawMemoryProvider"]
"""


def _hermes_home() -> Path:
    """Resolve the Hermes home directory.

    Honours ``HERMES_HOME`` env when set (Docker installs, alternative
    layouts); otherwise defaults to ``~/.hermes``.
    """
    explicit = os.environ.get("HERMES_HOME")
    if explicit:
        return Path(explicit).expanduser()
    return Path.home() / ".hermes"


def sidecar_path(hermes_home: Optional[Path] = None) -> Path:
    """Return the absolute path the sidecar will be installed at."""
    base = (hermes_home or _hermes_home()).expanduser()
    return base / "plugins" / "memory" / "totalreclaw" / "__init__.py"


def config_path(hermes_home: Optional[Path] = None) -> Path:
    """Return the path to ``~/.hermes/config.yaml`` (or HERMES_HOME variant)."""
    base = (hermes_home or _hermes_home()).expanduser()
    return base / "config.yaml"


def install_sidecar(hermes_home: Optional[Path] = None, *, force: bool = False) -> Path:
    """Drop the MemoryProvider sidecar shim.

    Args:
        hermes_home: override the Hermes home (default: $HERMES_HOME or ~/.hermes).
        force: overwrite even if the existing file lacks the managed marker.

    Returns:
        The path the sidecar was written to.

    Raises:
        RuntimeError: existing file present + lacks the managed marker +
            ``force`` not set. Refuses to clobber user-authored content.
    """
    path = sidecar_path(hermes_home)
    path.parent.mkdir(parents=True, exist_ok=True)

    if path.exists() and not force:
        existing = path.read_text(encoding="utf-8", errors="replace")
        if _SIDECAR_MARKER not in existing:
            raise RuntimeError(
                f"Refusing to overwrite hand-edited sidecar at {path}. "
                f"Pass force=True (or --force on the CLI) to replace it."
            )

    path.write_text(_SIDECAR_CONTENT, encoding="utf-8")
    logger.info("TotalReclaw MemoryProvider sidecar installed at %s", path)
    return path


def uninstall_sidecar(hermes_home: Optional[Path] = None) -> bool:
    """Remove the sidecar if it's a managed file. Returns True if removed."""
    path = sidecar_path(hermes_home)
    if not path.exists():
        return False
    existing = path.read_text(encoding="utf-8", errors="replace")
    if _SIDECAR_MARKER not in existing:
        raise RuntimeError(
            f"Refusing to uninstall hand-edited sidecar at {path}."
        )
    path.unlink()
    # Best-effort empty-parent cleanup (don't fail if siblings exist).
    try:
        path.parent.rmdir()
    except OSError:
        pass
    return True


_PROVIDER_LINE_RE = re.compile(r"^(\s*)provider\s*:\s*(\S+)\s*$", re.MULTILINE)
_MEMORY_BLOCK_RE = re.compile(
    r"^(memory:\s*\n(?:[ \t]+.*\n?)*)",
    re.MULTILINE,
)


def read_active_provider(hermes_home: Optional[Path] = None) -> str:
    """Return the active memory-provider name from Hermes config.

    Returns ``""`` (empty) when:
      - the config file does not exist (fresh install);
      - no ``memory.provider`` key is set;
      - the file is unreadable.

    Returns a lowercased provider name otherwise (e.g. ``"honcho"``,
    ``"byterover"``, ``"openviking"``, ``"totalreclaw"``, ``"none"``).
    """
    path = config_path(hermes_home)
    if not path.exists():
        return ""

    try:
        text = path.read_text(encoding="utf-8", errors="replace")
    except OSError:
        return ""

    block_match = _MEMORY_BLOCK_RE.search(text)
    if not block_match:
        return ""

    block = block_match.group(1)
    prov_match = _PROVIDER_LINE_RE.search(block)
    if not prov_match:
        return ""

    return prov_match.group(2).strip().lower()


def set_active_provider(
    provider: str,
    hermes_home: Optional[Path] = None,
) -> Path:
    """Write ``memory.provider: <provider>`` to Hermes config.

    Creates the config file + ``memory:`` block if missing. Updates the
    ``provider:`` line in-place if present. Preserves unrelated keys.

    Returns the config path written.
    """
    path = config_path(hermes_home)
    path.parent.mkdir(parents=True, exist_ok=True)

    if path.exists():
        try:
            text = path.read_text(encoding="utf-8", errors="replace")
        except OSError:
            text = ""
    else:
        text = ""

    block_match = _MEMORY_BLOCK_RE.search(text)
    if block_match:
        block = block_match.group(1)
        if _PROVIDER_LINE_RE.search(block):
            new_block = _PROVIDER_LINE_RE.sub(
                rf"\1provider: {provider}",
                block,
                count=1,
            )
        else:
            # memory: block exists but no provider key — append the line
            # at end of block (preserve trailing newline behaviour).
            stripped = block.rstrip("\n")
            new_block = stripped + f"\n  provider: {provider}\n"
        text = text[:block_match.start(1)] + new_block + text[block_match.end(1):]
    else:
        # No memory: block — append one. Preserve a single trailing newline
        # between any existing content and our block.
        sep = "" if (text == "" or text.endswith("\n")) else "\n"
        text = text + sep + f"memory:\n  provider: {provider}\n"

    path.write_text(text, encoding="utf-8")
    logger.info("TotalReclaw: set memory.provider=%s in %s", provider, path)
    return path


def install_and_activate(
    hermes_home: Optional[Path] = None,
    *,
    activate: bool = True,
    force: bool = False,
) -> dict:
    """High-level helper combining sidecar drop + optional activation.

    Returns a status dict with the same keys regardless of branch so
    callers (CLI / agent) can render a consistent confirmation.
    """
    sidecar = install_sidecar(hermes_home, force=force)
    previous = read_active_provider(hermes_home)
    activated = False
    if activate:
        set_active_provider("totalreclaw", hermes_home)
        activated = True

    return {
        "sidecar_path": str(sidecar),
        "previous_provider": previous or "",
        "active_provider": "totalreclaw" if activated else (previous or ""),
        "activated": activated,
    }
