"""Install TotalReclaw as a Hermes MemoryProvider (Path B — issue #275).

This module drops a one-file sidecar at
``$HERMES_HOME/plugins/totalreclaw/__init__.py`` so Hermes'
built-in memory-provider loader picks up :class:`TotalReclawMemoryProvider`
without needing an upstream API addition.

Why a sidecar
-------------
Hermes' plugin context (``ctx`` passed to ``register()``) does not
expose ``register_memory_provider`` — only tools and lifecycle hooks.
Memory providers are discovered by scanning ``$HERMES_HOME/plugins/<name>/``
(user-installed) for ``MemoryProvider`` subclasses — NOT the nested
``plugins/memory/<name>/`` layout, which is the *bundled* (in-tree)
location only. (Getting this path wrong was the 2026-06-10 split-brain
bug; see :func:`sidecar_path`.) The sidecar imports our class from
the installed ``totalreclaw`` PyPI package, so the heavy lifting stays
in the main distribution.

Resilient edition (issue #638, 2026-09-07)
------------------------------------------
The sidecar used to be a bare 3-line re-export stub. That had two
defects: it carried no ``register()`` (so when it replaced a git-plugin
bootstrap file, the *next* plugin reload silently dropped every
``totalreclaw_*`` tool + hook), and it had no bootstrap (so a Hermes
runtime regeneration that recreated the venv without the pip-installed
``totalreclaw`` package killed the import and the plugin vanished with
**no error anywhere** — Hermes does not surface an unmet ``requires:``).

``_SIDECAR_CONTENT`` is now a full, self-healing plugin file (the
rc.10 git-plugin bootstrap behaviour, ported): on ``ImportError`` it
makes one bounded attempt to reinstall the package into the RUNNING
interpreter's venv; if that fails it still loads in DEGRADED mode,
registering a ``totalreclaw_status`` tool that reports exactly what is
wrong and how to fix it. The state-dir writability probe from the git
bootstrap is deliberately NOT ported — it does not impede the two jobs
this file has (provider re-export + register delegation) and raising at
import time would take down provider discovery with it.

UX
--
Activation flow handled by the agent (see ``SKILL.md``):

  1. Read current provider via :func:`read_active_provider` (config grep —
     upstream ``hermes memory status --json`` is not yet released; see
     spec §"Open questions for upstream").
  2. If ``"none"`` / ``""`` / ``"totalreclaw"``: call
     :func:`install_sidecar` + :func:`set_active_provider` silently.
  3. If another provider is active: ask the user "switch or tools-only?".
     - **switch** → :func:`install_sidecar` + :func:`set_active_provider`
       (warn that the previous provider deactivates).
     - **tools-only** → :func:`install_sidecar` only; TR tools remain
       available, hooks don't fire because TR isn't the active provider.

All operations are idempotent: rerunning on an already-installed
sidecar overwrites with the current shim content (catches package
upgrades that change the import path) without disturbing other state.
That idempotent rewrite is also the healing path for boxes still
carrying the old bare stub: a single re-pair or one
``install-memory-provider --force`` replaces it with the resilient file.
"""
from __future__ import annotations

import logging
import os
import re
from pathlib import Path
from typing import Optional

logger = logging.getLogger(__name__)

# Generated comment: keep the marker line stable so future versions can
# detect a managed sidecar and refuse to clobber a hand-edited one.
_SIDECAR_MARKER = "# managed-by: totalreclaw.hermes.install_memory_provider"

# NOTE: plain string (not an f-string) — the template contains dict/brace
# literals for the degraded tool schema. The marker is prepended by
# concatenation so the template body needs no escaping.
_SIDECAR_CONTENT = _SIDECAR_MARKER + "\n" + '''\
"""Hermes plugin + MemoryProvider sidecar for TotalReclaw (resilient edition, #638).

Auto-generated by ``totalreclaw hermes install-memory-provider`` — do not
edit by hand; re-run the install command on package upgrade.

This file serves BOTH Hermes surfaces that live at
``$HERMES_HOME/plugins/totalreclaw/``:

* memory-provider discovery — Hermes scans ``plugins/<name>/`` for
  ``MemoryProvider`` subclasses; this module re-exports
  ``TotalReclawMemoryProvider`` from the installed ``totalreclaw``
  PyPI package.
* the plugin loader — ``plugin.yaml`` + ``register(ctx)``; this module
  defines ``register(ctx)`` delegating to ``totalreclaw.hermes.register``
  so every ``totalreclaw_*`` tool + lifecycle hook keeps working even
  where this sidecar has replaced a git-plugin bootstrap file.

Self-healing (the #638 failure mode): a Hermes runtime regeneration
recreates the venv WITHOUT pip-installed extras, so
``import totalreclaw`` fails and the old bare-stub sidecar made the
whole plugin vanish silently. Here an ImportError triggers ONE bounded
reinstall attempt into the RUNNING interpreter's venv; if that also
fails the module still finishes importing in DEGRADED mode —
``register(ctx)`` registers a ``totalreclaw_status`` tool that reports
what is wrong and how to fix it, instead of Hermes skipping the plugin
with no error anywhere.
"""
from __future__ import annotations

import logging
import subprocess
import sys

logger = logging.getLogger(__name__)

_LOAD_ERROR = None
TotalReclawMemoryProvider = None  # re-exported on the success path below

_DEGRADED_STATUS_SCHEMA = {
    "name": "totalreclaw_status",
    "description": (
        "Check TotalReclaw billing status, usage, and tier information. "
        "DEGRADED: the totalreclaw Python package is missing from this "
        "Hermes venv, so only this diagnostic tool is available."
    ),
    "parameters": {"type": "object", "properties": {}},
}


def _pip_install_totalreclaw():
    """One bounded attempt to (re)install the package into the RUNNING
    interpreter's venv (``sys.executable``). Returns ``None`` on success,
    an error string on failure. Never raises."""
    try:
        import pip  # noqa: F401
    except ImportError:
        try:
            subprocess.check_call(
                [sys.executable, "-m", "ensurepip", "--upgrade"],
                stdout=subprocess.DEVNULL,
                stderr=subprocess.DEVNULL,
            )
        except subprocess.CalledProcessError as exc:
            return f"venv lacks pip and ensurepip failed: {exc}"
    cmd = [
        sys.executable, "-m", "pip", "install",
        "--pre", "--no-cache-dir",
        "--index-url", "https://pypi.org/simple/",
        "--no-warn-script-location",
        "totalreclaw",
    ]
    try:
        proc = subprocess.run(
            cmd, stdout=subprocess.PIPE, stderr=subprocess.PIPE,
            text=True, check=False,
        )
    except OSError as exc:
        return f"could not run pip: {exc}"
    if proc.returncode != 0:
        tail = (proc.stderr or "").strip()[-1500:]
        return f"`{' '.join(cmd)}` exited {proc.returncode}. stderr tail:\\n{tail}"
    return None


def _install_skill():
    """Mirror the package's SKILL.md into the Hermes skills dir (port of
    the rc.10 git-plugin bootstrap step). Best-effort + idempotent."""
    try:
        from importlib.resources import files as _resource_files
        src_text = _resource_files("totalreclaw.hermes").joinpath(
            "SKILL.md"
        ).read_text(encoding="utf-8")
        from hermes_constants import get_hermes_home
        hermes_home = get_hermes_home()
    except (ImportError, FileNotFoundError, OSError) as exc:
        logger.debug("sidecar: SKILL.md mirror skipped: %s", exc)
        return
    try:
        import shutil
        legacy_dir = hermes_home / "skills" / "devops" / "totalreclaw-memory"
        if legacy_dir.exists():
            shutil.rmtree(legacy_dir, ignore_errors=True)
        skills_dir = hermes_home / "skills" / "memory" / "totalreclaw"
        dst = skills_dir / "SKILL.md"
        if dst.exists() and dst.read_text(encoding="utf-8") == src_text:
            return
        skills_dir.mkdir(parents=True, exist_ok=True)
        dst.write_text(src_text, encoding="utf-8")
        logger.info("sidecar: installed TotalReclaw skill to %s", dst)
    except OSError:
        logger.debug("sidecar: SKILL.md write skipped", exc_info=True)


try:
    from totalreclaw.hermes.memory_provider import TotalReclawMemoryProvider  # noqa: F401
    _IMPORT_OK = True
except ImportError as _first_err:
    _IMPORT_OK = False
    _heal_err = _pip_install_totalreclaw()
    if _heal_err is None:
        try:
            from totalreclaw.hermes.memory_provider import TotalReclawMemoryProvider  # noqa: F401
            _IMPORT_OK = True
        except ImportError as _second_err:
            _LOAD_ERROR = (
                "self-heal reinstall reported success but import still "
                f"fails: {_second_err}"
            )
    else:
        _LOAD_ERROR = (
            f"`import totalreclaw` failed ({_first_err}) and the self-heal "
            f"reinstall could not run: {_heal_err}"
        )

if _IMPORT_OK:
    _install_skill()

    def register(ctx):
        """Hermes calls this on plugin load — delegate to the package's
        full register (all ``totalreclaw_*`` tools + lifecycle hooks)."""
        from totalreclaw.hermes import register as _register
        return _register(ctx)

    __all__ = ["TotalReclawMemoryProvider", "register"]
else:
    logger.error(
        "TotalReclaw sidecar loaded DEGRADED — the totalreclaw package is "
        "missing from this Hermes venv and the self-heal reinstall failed. "
        "Only a diagnostic totalreclaw_status tool will be registered. %s",
        _LOAD_ERROR,
    )

    def register(ctx):
        """Degraded register (issue #638): make the failure LOUD. The
        agent gets a ``totalreclaw_status`` tool reporting the missing
        package + the fix command, instead of every TotalReclaw tool
        vanishing with no error anywhere."""

        def _degraded_status(args, **kw):
            return {
                "ok": False,
                "degraded": True,
                "error": (
                    "The totalreclaw Python package is missing from this "
                    "Hermes venv (likely wiped by a Hermes runtime "
                    "regeneration). Memory tools are unavailable until it "
                    "is reinstalled."
                ),
                "fix": (
                    "Reinstall with: "
                    + sys.executable
                    + " -m pip install --pre totalreclaw   (then restart "
                    "the Hermes gateway), or re-run: totalreclaw hermes "
                    "install-memory-provider --force"
                ),
                "detail": _LOAD_ERROR,
            }

        try:
            ctx.register_tool(
                name="totalreclaw_status",
                toolset="totalreclaw",
                schema=_DEGRADED_STATUS_SCHEMA,
                handler=_degraded_status,
            )
        except Exception:
            logger.exception(
                "sidecar: degraded status tool registration failed — "
                "TotalReclaw is fully unavailable on this gateway"
            )

    __all__ = ["register"]
'''


def _hermes_home() -> Path:
    """Resolve the Hermes home directory.

    Honours ``HERMES_HOME`` env when set (Docker installs, alternative
    layouts); otherwise defaults to ``~/.hermes``.
    """
    explicit = os.environ.get("HERMES_HOME")
    if explicit:
        return Path(explicit).expanduser()
    return Path.home() / ".hermes"


def _legacy_sidecar_path(hermes_home: Optional[Path] = None) -> Path:
    """The pre-2026-06-10 (wrong) install location.

    Hermes never scanned this nested path, so a sidecar here was inert. We
    clean it up on (re)install so an upgraded vault doesn't keep a dead,
    confusing file under ``plugins/memory/totalreclaw/``.
    """
    base = (hermes_home or _hermes_home()).expanduser()
    return base / "plugins" / "memory" / "totalreclaw" / "__init__.py"


def _migrate_legacy_sidecar(hermes_home: Optional[Path] = None) -> bool:
    """Remove a stale managed sidecar at the old ``plugins/memory/totalreclaw/``
    location. Only deletes our own managed file (marker-gated); leaves any
    hand-edited file untouched. Returns True if something was removed."""
    legacy = _legacy_sidecar_path(hermes_home)
    if not legacy.exists():
        return False
    try:
        if _SIDECAR_MARKER not in legacy.read_text(encoding="utf-8", errors="replace"):
            return False  # not ours — don't touch
        legacy.unlink()
        try:
            legacy.parent.rmdir()  # best-effort empty-parent cleanup
        except OSError:
            pass
        logger.info("Removed stale legacy sidecar at %s", legacy)
        return True
    except OSError:
        return False


def sidecar_path(hermes_home: Optional[Path] = None) -> Path:
    """Return the absolute path the sidecar will be installed at.

    IMPORTANT — discovery path (fixed 2026-06-10): Hermes discovers
    *user-installed* memory providers by scanning ``$HERMES_HOME/plugins/<name>/``
    (``plugins.memory.__init__._get_user_plugins_dir`` returns
    ``$HERMES_HOME/plugins`` and ``find_provider_dir`` looks one level deep).
    The ``plugins/memory/<name>/`` layout is the *bundled* (in-tree) location
    only. We previously wrote the sidecar to ``$HERMES_HOME/plugins/memory/totalreclaw/``,
    mirroring the bundled layout — but Hermes never scans that nested path, so
    ``load_memory_provider("totalreclaw")`` returned None, ``memory.provider:
    totalreclaw`` dangled, and the builtin provider ran instead (split-brain).
    Verified on a live box: ``$HERMES_HOME/plugins/totalreclaw/`` resolves and
    loads; ``$HERMES_HOME/plugins/memory/totalreclaw/`` does not.
    """
    base = (hermes_home or _hermes_home()).expanduser()
    return base / "plugins" / "totalreclaw" / "__init__.py"


def config_path(hermes_home: Optional[Path] = None) -> Path:
    """Return the path to ``~/.hermes/config.yaml`` (or HERMES_HOME variant)."""
    base = (hermes_home or _hermes_home()).expanduser()
    return base / "config.yaml"


def install_sidecar(hermes_home: Optional[Path] = None, *, force: bool = False) -> Path:
    """Drop the MemoryProvider sidecar shim.

    Args:
        hermes_home: override the Hermes home (default: $HERMES_HOME or ~/.hermes).
        force: overwrite even if the existing file lacks the managed marker.

    Returns:
        The path the sidecar was written to.

    Raises:
        RuntimeError: existing file present + lacks the managed marker +
            ``force`` not set. Refuses to clobber user-authored content.
    """
    # Migrate: drop the stale sidecar from the old (never-scanned) location
    # so upgraded vaults don't carry a dead file under plugins/memory/.
    _migrate_legacy_sidecar(hermes_home)

    path = sidecar_path(hermes_home)
    path.parent.mkdir(parents=True, exist_ok=True)

    if path.exists() and not force:
        existing = path.read_text(encoding="utf-8", errors="replace")
        if _SIDECAR_MARKER not in existing:
            raise RuntimeError(
                f"Refusing to overwrite hand-edited sidecar at {path}. "
                f"Pass force=True (or --force on the CLI) to replace it."
            )

    path.write_text(_SIDECAR_CONTENT, encoding="utf-8")
    logger.info("TotalReclaw MemoryProvider sidecar installed at %s", path)
    return path


def uninstall_sidecar(hermes_home: Optional[Path] = None) -> bool:
    """Remove the sidecar if it's a managed file. Returns True if removed."""
    path = sidecar_path(hermes_home)
    if not path.exists():
        return False
    existing = path.read_text(encoding="utf-8", errors="replace")
    if _SIDECAR_MARKER not in existing:
        raise RuntimeError(
            f"Refusing to uninstall hand-edited sidecar at {path}."
        )
    path.unlink()
    # Best-effort empty-parent cleanup (don't fail if siblings exist).
    try:
        path.parent.rmdir()
    except OSError:
        pass
    return True


# Trailing `[ \t]*$` (horizontal whitespace only) is load-bearing: `\s*$`
# would let the engine consume the line-terminating `\n` (since `\s` matches
# newlines and `$` matches end-of-string), so the replacement would smash the
# value into the next top-level key. See test_issue_351_*.
_PROVIDER_LINE_RE = re.compile(r"^(\s*)provider\s*:\s*(\S+)[ \t]*$", re.MULTILINE)
_MEMORY_BLOCK_RE = re.compile(
    r"^(memory:\s*\n(?:[ \t]+.*\n?)*)",
    re.MULTILINE,
)


def read_active_provider(hermes_home: Optional[Path] = None) -> str:
    """Return the active memory-provider name from Hermes config.

    Returns ``""`` (empty) when:
      - the config file does not exist (fresh install);
      - no ``memory.provider`` key is set;
      - the file is unreadable.

    Returns a lowercased provider name otherwise (e.g. ``"honcho"``,
    ``"byterover"``, ``"openviking"``, ``"totalreclaw"``, ``"none"``).
    """
    path = config_path(hermes_home)
    if not path.exists():
        return ""

    try:
        text = path.read_text(encoding="utf-8", errors="replace")
    except OSError:
        return ""

    block_match = _MEMORY_BLOCK_RE.search(text)
    if not block_match:
        return ""

    block = block_match.group(1)
    prov_match = _PROVIDER_LINE_RE.search(block)
    if not prov_match:
        return ""

    return prov_match.group(2).strip().lower()


def set_active_provider(
    provider: str,
    hermes_home: Optional[Path] = None,
) -> Path:
    """Write ``memory.provider: <provider>`` to Hermes config.

    Creates the config file + ``memory:`` block if missing. Updates the
    ``provider:`` line in-place if present. Preserves unrelated keys.

    Returns the config path written.
    """
    path = config_path(hermes_home)
    path.parent.mkdir(parents=True, exist_ok=True)

    if path.exists():
        try:
            text = path.read_text(encoding="utf-8", errors="replace")
        except OSError:
            text = ""
    else:
        text = ""

    block_match = _MEMORY_BLOCK_RE.search(text)
    if block_match:
        block = block_match.group(1)
        if _PROVIDER_LINE_RE.search(block):
            new_block = _PROVIDER_LINE_RE.sub(
                rf"\1provider: {provider}",
                block,
                count=1,
            )
        else:
            # memory: block exists but no provider key — append the line
            # at end of block (preserve trailing newline behaviour).
            stripped = block.rstrip("\n")
            new_block = stripped + f"\n  provider: {provider}\n"
        text = text[:block_match.start(1)] + new_block + text[block_match.end(1):]
    else:
        # No memory: block — append one. Preserve a single trailing newline
        # between any existing content and our block.
        sep = "" if (text == "" or text.endswith("\n")) else "\n"
        text = text + sep + f"memory:\n  provider: {provider}\n"

    path.write_text(text, encoding="utf-8")
    logger.info("TotalReclaw: set memory.provider=%s in %s", provider, path)
    return path


def _memory_key_re(key: str) -> "re.Pattern[str]":
    """Match ``<indent><key>: <value>`` inside the memory block."""
    return re.compile(rf"^(\s*){re.escape(key)}\s*:\s*(\S+)[ \t]*$", re.MULTILINE)


def _set_memory_key(text: str, key: str, value: str) -> str:
    """Return *text* with ``memory.<key>: <value>`` set.

    Replaces the key in-place if present in the ``memory:`` block, appends it
    to the block if the block exists but the key doesn't, or creates a
    ``memory:`` block if there is none. Mirrors :func:`set_active_provider`'s
    YAML-surgery approach (no full YAML parse — preserves comments/ordering).
    """
    key_re = _memory_key_re(key)
    block_match = _MEMORY_BLOCK_RE.search(text)
    if block_match:
        block = block_match.group(1)
        if key_re.search(block):
            new_block = key_re.sub(rf"\g<1>{key}: {value}", block, count=1)
        else:
            stripped = block.rstrip("\n")
            new_block = stripped + f"\n  {key}: {value}\n"
        return text[: block_match.start(1)] + new_block + text[block_match.end(1):]
    sep = "" if (text == "" or text.endswith("\n")) else "\n"
    return text + sep + f"memory:\n  {key}: {value}\n"


def disable_builtin_memory(hermes_home: Optional[Path] = None) -> Path:
    """Silence Hermes' builtin local memory so TotalReclaw is the sole system.

    Sets ``memory_enabled: false`` AND ``user_profile_enabled: false`` in the
    ``memory:`` block. Hermes loads its builtin ``MemoryStore`` (which reads +
    injects ``~/.hermes/memories/MEMORY.md`` and maintains ``~/.hermes/profiles/``)
    when *either* flag is true (``agent_init.py``), so both must be false to
    fully quiet it. TotalReclaw's own auto-recall/extract runs via its lifecycle
    hooks, which are independent of these flags — so disabling the builtin does
    NOT disable TotalReclaw; it just removes the parallel local store
    (the 2026-06-10 split-brain). ``provider: builtin`` (set by the user) is the
    explicit opt-in to switch back to local files.

    Returns the config path written.
    """
    path = config_path(hermes_home)
    path.parent.mkdir(parents=True, exist_ok=True)
    text = ""
    if path.exists():
        try:
            text = path.read_text(encoding="utf-8", errors="replace")
        except OSError:
            text = ""
    text = _set_memory_key(text, "memory_enabled", "false")
    text = _set_memory_key(text, "user_profile_enabled", "false")
    path.write_text(text, encoding="utf-8")
    logger.info(
        "TotalReclaw: disabled builtin memory (memory_enabled=false, "
        "user_profile_enabled=false) in %s",
        path,
    )
    return path


def install_and_activate(
    hermes_home: Optional[Path] = None,
    *,
    activate: bool = True,
    force: bool = False,
) -> dict:
    """High-level helper combining sidecar drop + optional activation.

    Returns a status dict with the same keys regardless of branch so
    callers (CLI / agent) can render a consistent confirmation.
    """
    sidecar = install_sidecar(hermes_home, force=force)
    previous = read_active_provider(hermes_home)
    activated = False
    builtin_disabled = False
    if activate:
        set_active_provider("totalreclaw", hermes_home)
        activated = True
        # Make TotalReclaw the SOLE memory system: silence the builtin local
        # store so it stops loading/injecting MEMORY.md + maintaining local
        # profiles in parallel (the split-brain). TR keeps running via its own
        # lifecycle hooks. Switching back to local files = user sets
        # `memory.provider: builtin` explicitly.
        disable_builtin_memory(hermes_home)
        builtin_disabled = True

    return {
        "sidecar_path": str(sidecar),
        "previous_provider": previous or "",
        "active_provider": "totalreclaw" if activated else (previous or ""),
        "activated": activated,
        "builtin_disabled": builtin_disabled,
    }
