"""Install TotalReclaw as a Hermes MemoryProvider (Path B — issue #275).

This module drops a one-file sidecar shim at
``$HERMES_HOME/plugins/totalreclaw/__init__.py`` so Hermes'
built-in memory-provider loader picks up :class:`TotalReclawMemoryProvider`
without needing an upstream API addition.

Why a sidecar
-------------
Hermes' plugin context (``ctx`` passed to ``register()``) does not
expose ``register_memory_provider`` — only tools and lifecycle hooks.
Memory providers are discovered by scanning ``$HERMES_HOME/plugins/<name>/``
(user-installed) for ``MemoryProvider`` subclasses — NOT the nested
``plugins/memory/<name>/`` layout, which is the *bundled* (in-tree)
location only. (Getting this path wrong was the 2026-06-10 split-brain
bug; see :func:`sidecar_path`.) The sidecar imports our class from
the installed ``totalreclaw`` PyPI package, so the heavy lifting stays
in the main distribution and the on-disk file is a 3-line stub.

UX
--
Activation flow handled by the agent (see ``SKILL.md``):

  1. Read current provider via :func:`read_active_provider` (config grep —
     upstream ``hermes memory status --json`` is not yet released; see
     spec §"Open questions for upstream").
  2. If ``"none"`` / ``""`` / ``"totalreclaw"``: call
     :func:`install_sidecar` + :func:`set_active_provider` silently.
  3. If another provider is active: ask the user "switch or tools-only?".
     - **switch** → :func:`install_sidecar` + :func:`set_active_provider`
       (warn that the previous provider deactivates).
     - **tools-only** → :func:`install_sidecar` only; TR tools remain
       available, hooks don't fire because TR isn't the active provider.

All operations are idempotent: rerunning on an already-installed
sidecar overwrites with the current shim content (catches package
upgrades that change the import path) without disturbing other state.
"""
from __future__ import annotations

import logging
import os
import re
from pathlib import Path
from typing import Optional

logger = logging.getLogger(__name__)

# Generated comment: keep the marker line stable so future versions can
# detect a managed sidecar and refuse to clobber a hand-edited one.
_SIDECAR_MARKER = "# managed-by: totalreclaw.hermes.install_memory_provider"

_SIDECAR_CONTENT = f"""\
{_SIDECAR_MARKER}
\"\"\"Hermes MemoryProvider sidecar for TotalReclaw.

This file is auto-generated by ``totalreclaw hermes install-memory-provider``.
It re-exports :class:`TotalReclawMemoryProvider` from the installed
``totalreclaw`` PyPI package so Hermes' ``$HERMES_HOME/plugins/<name>/``
loader can discover it.

Do not edit by hand — re-run the install command on package upgrade.
\"\"\"
from totalreclaw.hermes.memory_provider import TotalReclawMemoryProvider

__all__ = ["TotalReclawMemoryProvider"]
"""


def _hermes_home() -> Path:
    """Resolve the Hermes home directory.

    Honours ``HERMES_HOME`` env when set (Docker installs, alternative
    layouts); otherwise defaults to ``~/.hermes``.
    """
    explicit = os.environ.get("HERMES_HOME")
    if explicit:
        return Path(explicit).expanduser()
    return Path.home() / ".hermes"


def _legacy_sidecar_path(hermes_home: Optional[Path] = None) -> Path:
    """The pre-2026-06-10 (wrong) install location.

    Hermes never scanned this nested path, so a sidecar here was inert. We
    clean it up on (re)install so an upgraded vault doesn't keep a dead,
    confusing file under ``plugins/memory/totalreclaw/``.
    """
    base = (hermes_home or _hermes_home()).expanduser()
    return base / "plugins" / "memory" / "totalreclaw" / "__init__.py"


def _migrate_legacy_sidecar(hermes_home: Optional[Path] = None) -> bool:
    """Remove a stale managed sidecar at the old ``plugins/memory/totalreclaw/``
    location. Only deletes our own managed file (marker-gated); leaves any
    hand-edited file untouched. Returns True if something was removed."""
    legacy = _legacy_sidecar_path(hermes_home)
    if not legacy.exists():
        return False
    try:
        if _SIDECAR_MARKER not in legacy.read_text(encoding="utf-8", errors="replace"):
            return False  # not ours — don't touch
        legacy.unlink()
        try:
            legacy.parent.rmdir()  # best-effort empty-parent cleanup
        except OSError:
            pass
        logger.info("Removed stale legacy sidecar at %s", legacy)
        return True
    except OSError:
        return False


def sidecar_path(hermes_home: Optional[Path] = None) -> Path:
    """Return the absolute path the sidecar will be installed at.

    IMPORTANT — discovery path (fixed 2026-06-10): Hermes discovers
    *user-installed* memory providers by scanning ``$HERMES_HOME/plugins/<name>/``
    (``plugins.memory.__init__._get_user_plugins_dir`` returns
    ``$HERMES_HOME/plugins`` and ``find_provider_dir`` looks one level deep).
    The ``plugins/memory/<name>/`` layout is the *bundled* (in-tree) location
    only. We previously wrote the sidecar to ``$HERMES_HOME/plugins/memory/totalreclaw/``,
    mirroring the bundled layout — but Hermes never scans that nested path, so
    ``load_memory_provider("totalreclaw")`` returned None, ``memory.provider:
    totalreclaw`` dangled, and the builtin provider ran instead (split-brain).
    Verified on a live box: ``$HERMES_HOME/plugins/totalreclaw/`` resolves and
    loads; ``$HERMES_HOME/plugins/memory/totalreclaw/`` does not.
    """
    base = (hermes_home or _hermes_home()).expanduser()
    return base / "plugins" / "totalreclaw" / "__init__.py"


def config_path(hermes_home: Optional[Path] = None) -> Path:
    """Return the path to ``~/.hermes/config.yaml`` (or HERMES_HOME variant)."""
    base = (hermes_home or _hermes_home()).expanduser()
    return base / "config.yaml"


def install_sidecar(hermes_home: Optional[Path] = None, *, force: bool = False) -> Path:
    """Drop the MemoryProvider sidecar shim.

    Args:
        hermes_home: override the Hermes home (default: $HERMES_HOME or ~/.hermes).
        force: overwrite even if the existing file lacks the managed marker.

    Returns:
        The path the sidecar was written to.

    Raises:
        RuntimeError: existing file present + lacks the managed marker +
            ``force`` not set. Refuses to clobber user-authored content.
    """
    # Migrate: drop the stale sidecar from the old (never-scanned) location
    # so upgraded vaults don't carry a dead file under plugins/memory/.
    _migrate_legacy_sidecar(hermes_home)

    path = sidecar_path(hermes_home)
    path.parent.mkdir(parents=True, exist_ok=True)

    if path.exists() and not force:
        existing = path.read_text(encoding="utf-8", errors="replace")
        if _SIDECAR_MARKER not in existing:
            raise RuntimeError(
                f"Refusing to overwrite hand-edited sidecar at {path}. "
                f"Pass force=True (or --force on the CLI) to replace it."
            )

    path.write_text(_SIDECAR_CONTENT, encoding="utf-8")
    logger.info("TotalReclaw MemoryProvider sidecar installed at %s", path)
    return path


def uninstall_sidecar(hermes_home: Optional[Path] = None) -> bool:
    """Remove the sidecar if it's a managed file. Returns True if removed."""
    path = sidecar_path(hermes_home)
    if not path.exists():
        return False
    existing = path.read_text(encoding="utf-8", errors="replace")
    if _SIDECAR_MARKER not in existing:
        raise RuntimeError(
            f"Refusing to uninstall hand-edited sidecar at {path}."
        )
    path.unlink()
    # Best-effort empty-parent cleanup (don't fail if siblings exist).
    try:
        path.parent.rmdir()
    except OSError:
        pass
    return True


# Trailing `[ \t]*$` (horizontal whitespace only) is load-bearing: `\s*$`
# would let the engine consume the line-terminating `\n` (since `\s` matches
# newlines and `$` matches end-of-string), so the replacement would smash the
# value into the next top-level key. See test_issue_351_*.
_PROVIDER_LINE_RE = re.compile(r"^(\s*)provider\s*:\s*(\S+)[ \t]*$", re.MULTILINE)
_MEMORY_BLOCK_RE = re.compile(
    r"^(memory:\s*\n(?:[ \t]+.*\n?)*)",
    re.MULTILINE,
)


def read_active_provider(hermes_home: Optional[Path] = None) -> str:
    """Return the active memory-provider name from Hermes config.

    Returns ``""`` (empty) when:
      - the config file does not exist (fresh install);
      - no ``memory.provider`` key is set;
      - the file is unreadable.

    Returns a lowercased provider name otherwise (e.g. ``"honcho"``,
    ``"byterover"``, ``"openviking"``, ``"totalreclaw"``, ``"none"``).
    """
    path = config_path(hermes_home)
    if not path.exists():
        return ""

    try:
        text = path.read_text(encoding="utf-8", errors="replace")
    except OSError:
        return ""

    block_match = _MEMORY_BLOCK_RE.search(text)
    if not block_match:
        return ""

    block = block_match.group(1)
    prov_match = _PROVIDER_LINE_RE.search(block)
    if not prov_match:
        return ""

    return prov_match.group(2).strip().lower()


def set_active_provider(
    provider: str,
    hermes_home: Optional[Path] = None,
) -> Path:
    """Write ``memory.provider: <provider>`` to Hermes config.

    Creates the config file + ``memory:`` block if missing. Updates the
    ``provider:`` line in-place if present. Preserves unrelated keys.

    Returns the config path written.
    """
    path = config_path(hermes_home)
    path.parent.mkdir(parents=True, exist_ok=True)

    if path.exists():
        try:
            text = path.read_text(encoding="utf-8", errors="replace")
        except OSError:
            text = ""
    else:
        text = ""

    block_match = _MEMORY_BLOCK_RE.search(text)
    if block_match:
        block = block_match.group(1)
        if _PROVIDER_LINE_RE.search(block):
            new_block = _PROVIDER_LINE_RE.sub(
                rf"\1provider: {provider}",
                block,
                count=1,
            )
        else:
            # memory: block exists but no provider key — append the line
            # at end of block (preserve trailing newline behaviour).
            stripped = block.rstrip("\n")
            new_block = stripped + f"\n  provider: {provider}\n"
        text = text[:block_match.start(1)] + new_block + text[block_match.end(1):]
    else:
        # No memory: block — append one. Preserve a single trailing newline
        # between any existing content and our block.
        sep = "" if (text == "" or text.endswith("\n")) else "\n"
        text = text + sep + f"memory:\n  provider: {provider}\n"

    path.write_text(text, encoding="utf-8")
    logger.info("TotalReclaw: set memory.provider=%s in %s", provider, path)
    return path


def _memory_key_re(key: str) -> "re.Pattern[str]":
    """Match ``<indent><key>: <value>`` inside the memory block."""
    return re.compile(rf"^(\s*){re.escape(key)}\s*:\s*(\S+)[ \t]*$", re.MULTILINE)


def _set_memory_key(text: str, key: str, value: str) -> str:
    """Return *text* with ``memory.<key>: <value>`` set.

    Replaces the key in-place if present in the ``memory:`` block, appends it
    to the block if the block exists but the key doesn't, or creates a
    ``memory:`` block if there is none. Mirrors :func:`set_active_provider`'s
    YAML-surgery approach (no full YAML parse — preserves comments/ordering).
    """
    key_re = _memory_key_re(key)
    block_match = _MEMORY_BLOCK_RE.search(text)
    if block_match:
        block = block_match.group(1)
        if key_re.search(block):
            new_block = key_re.sub(rf"\g<1>{key}: {value}", block, count=1)
        else:
            stripped = block.rstrip("\n")
            new_block = stripped + f"\n  {key}: {value}\n"
        return text[: block_match.start(1)] + new_block + text[block_match.end(1):]
    sep = "" if (text == "" or text.endswith("\n")) else "\n"
    return text + sep + f"memory:\n  {key}: {value}\n"


def disable_builtin_memory(hermes_home: Optional[Path] = None) -> Path:
    """Silence Hermes' builtin local memory so TotalReclaw is the sole system.

    Sets ``memory_enabled: false`` AND ``user_profile_enabled: false`` in the
    ``memory:`` block. Hermes loads its builtin ``MemoryStore`` (which reads +
    injects ``~/.hermes/memories/MEMORY.md`` and maintains ``~/.hermes/profiles/``)
    when *either* flag is true (``agent_init.py``), so both must be false to
    fully quiet it. TotalReclaw's own auto-recall/extract runs via its lifecycle
    hooks, which are independent of these flags — so disabling the builtin does
    NOT disable TotalReclaw; it just removes the parallel local store
    (the 2026-06-10 split-brain). ``provider: builtin`` (set by the user) is the
    explicit opt-in to switch back to local files.

    Returns the config path written.
    """
    path = config_path(hermes_home)
    path.parent.mkdir(parents=True, exist_ok=True)
    text = ""
    if path.exists():
        try:
            text = path.read_text(encoding="utf-8", errors="replace")
        except OSError:
            text = ""
    text = _set_memory_key(text, "memory_enabled", "false")
    text = _set_memory_key(text, "user_profile_enabled", "false")
    path.write_text(text, encoding="utf-8")
    logger.info(
        "TotalReclaw: disabled builtin memory (memory_enabled=false, "
        "user_profile_enabled=false) in %s",
        path,
    )
    return path


def install_and_activate(
    hermes_home: Optional[Path] = None,
    *,
    activate: bool = True,
    force: bool = False,
) -> dict:
    """High-level helper combining sidecar drop + optional activation.

    Returns a status dict with the same keys regardless of branch so
    callers (CLI / agent) can render a consistent confirmation.
    """
    sidecar = install_sidecar(hermes_home, force=force)
    previous = read_active_provider(hermes_home)
    activated = False
    builtin_disabled = False
    if activate:
        set_active_provider("totalreclaw", hermes_home)
        activated = True
        # Make TotalReclaw the SOLE memory system: silence the builtin local
        # store so it stops loading/injecting MEMORY.md + maintaining local
        # profiles in parallel (the split-brain). TR keeps running via its own
        # lifecycle hooks. Switching back to local files = user sets
        # `memory.provider: builtin` explicitly.
        disable_builtin_memory(hermes_home)
        builtin_disabled = True

    return {
        "sidecar_path": str(sidecar),
        "previous_provider": previous or "",
        "active_provider": "totalreclaw" if activated else (previous or ""),
        "activated": activated,
        "builtin_disabled": builtin_disabled,
    }
