/**
 * v1 blob round-trip tests: buildV1ClaimBlob + readBlobUnified.
 *
 * Together these cover the MCP-server write → decrypt → parse path for the
 * Memory Taxonomy v1 inner-blob format. Crypto is not exercised here — just
 * the JSON canonicalisation and the v1 vs v0 vs legacy parser routing.
 */

import { buildV1ClaimBlob, readBlobUnified, readClaimFromBlob } from '../src/claims-helper';

describe('buildV1ClaimBlob', () => {
  test('emits a canonical v1 claim with required fields', () => {
    const blob = buildV1ClaimBlob({
      text: 'prefers coffee over tea',
      type: 'preference',
      source: 'user',
    });
    const parsed = JSON.parse(blob);
    expect(parsed.text).toBe('prefers coffee over tea');
    expect(parsed.type).toBe('preference');
    expect(parsed.source).toBe('user');
    // Required fields generated by the builder
    expect(typeof parsed.id).toBe('string');
    expect(typeof parsed.created_at).toBe('string');
    // schema_version is skipped on serialization when equal to default; that's
    // fine — the validator injects it on parse.
    expect(parsed.schema_version === undefined || parsed.schema_version === '1.0').toBe(true);
  });

  test('preserves supplied id + created_at', () => {
    const blob = buildV1ClaimBlob({
      text: 'lives in Lisbon',
      type: 'claim',
      source: 'user',
      id: 'custom-uuid',
      createdAt: '2026-04-17T00:00:00Z',
    });
    const parsed = JSON.parse(blob);
    expect(parsed.id).toBe('custom-uuid');
    expect(parsed.created_at).toBe('2026-04-17T00:00:00Z');
  });

  test('omits default scope + volatility (skip_serializing_if)', () => {
    const blob = buildV1ClaimBlob({
      text: 'default',
      type: 'claim',
      source: 'user',
      scope: 'unspecified',     // default — omitted
      volatility: 'updatable',  // default — omitted
    });
    const parsed = JSON.parse(blob);
    expect(parsed.scope).toBeUndefined();
    expect(parsed.volatility).toBeUndefined();
  });

  test('serializes non-default scope, volatility, reasoning, entities', () => {
    const blob = buildV1ClaimBlob({
      text: 'chose PostgreSQL',
      type: 'claim',
      source: 'user-inferred',
      scope: 'work',
      volatility: 'stable',
      reasoning: 'data is relational and needs ACID',
      entities: [{ name: 'PostgreSQL', type: 'tool', role: 'chosen' }],
      importance: 8,
      confidence: 0.92,
    });
    const parsed = JSON.parse(blob);
    expect(parsed.scope).toBe('work');
    expect(parsed.volatility).toBe('stable');
    expect(parsed.reasoning).toBe('data is relational and needs ACID');
    expect(parsed.entities).toHaveLength(1);
    expect(parsed.entities[0].name).toBe('PostgreSQL');
    expect(parsed.importance).toBe(8);
    expect(parsed.confidence).toBe(0.92);
  });

  test('supersededBy is serialized as superseded_by', () => {
    const blob = buildV1ClaimBlob({
      text: 'new fact',
      type: 'claim',
      source: 'user',
      supersededBy: 'old-id-abc',
    });
    const parsed = JSON.parse(blob);
    expect(parsed.superseded_by).toBe('old-id-abc');
  });

  test('throws on invalid input (would fail validation)', () => {
    expect(() => {
      buildV1ClaimBlob({
        text: '',             // valid per serde (no min-len constraint in Rust struct)
        type: 'claim' as any,
        source: 'invalid' as any,
      });
    }).toThrow();
  });
});

describe('readBlobUnified — v1 path', () => {
  test('round-trips a v1 blob: build → parse', () => {
    const blob = buildV1ClaimBlob({
      text: 'hello world',
      type: 'directive',
      source: 'assistant',
      scope: 'work',
      reasoning: 'because',
      importance: 7,
    });
    const parsed = readBlobUnified(blob);
    expect(parsed.text).toBe('hello world');
    expect(parsed.importance).toBe(7);
    expect(parsed.category).toBe('rule'); // directive → short key rule
    expect(parsed.v1).toBeDefined();
    expect(parsed.v1!.type).toBe('directive');
    expect(parsed.v1!.source).toBe('assistant');
    expect(parsed.v1!.scope).toBe('work');
    expect(parsed.v1!.reasoning).toBe('because');
  });

  test('maps directive → short-key rule + preference → short-key pref', () => {
    const directiveBlob = buildV1ClaimBlob({
      text: 'x',
      type: 'directive',
      source: 'user',
    });
    expect(readBlobUnified(directiveBlob).category).toBe('rule');

    const prefBlob = buildV1ClaimBlob({
      text: 'y',
      type: 'preference',
      source: 'user',
    });
    expect(readBlobUnified(prefBlob).category).toBe('pref');
  });

  test('v0 short-key canonical blob still parses correctly', () => {
    const v0Blob = JSON.stringify({
      t: 'legacy short-key',
      c: 'rule',
      cf: 0.9,
      i: 8,
      sa: 'mcp-server',
      ea: '2026-01-01T00:00:00Z',
    });
    const parsed = readBlobUnified(v0Blob);
    expect(parsed.text).toBe('legacy short-key');
    expect(parsed.importance).toBe(8);
    expect(parsed.category).toBe('rule');
    expect(parsed.v1).toBeUndefined();
  });

  test('plugin-legacy {text, metadata} parses correctly', () => {
    const legacy = JSON.stringify({
      text: 'older fact',
      metadata: { type: 'preference', importance: 0.6, source: 'mcp_remember' },
    });
    const parsed = readBlobUnified(legacy);
    expect(parsed.text).toBe('older fact');
    expect(parsed.importance).toBe(6);
    expect(parsed.category).toBe('preference');
    expect(parsed.v1).toBeUndefined();
  });

  test('raw text falls through to text-as-is with neutral defaults', () => {
    const parsed = readBlobUnified('not json');
    expect(parsed.text).toBe('not json');
    expect(parsed.importance).toBe(5);
    expect(parsed.category).toBe('fact');
    expect(parsed.v1).toBeUndefined();
  });
});

describe('readClaimFromBlob still works on legacy paths (no regression)', () => {
  test('v0 canonical', () => {
    const v0 = JSON.stringify({
      t: 'text',
      c: 'pref',
      cf: 0.9,
      i: 6,
      sa: 'mcp-server',
      ea: '2026-01-01T00:00:00Z',
    });
    const parsed = readClaimFromBlob(v0);
    expect(parsed.text).toBe('text');
    expect(parsed.importance).toBe(6);
  });
});
