"""``derived-bundle-v1`` cross-language parity test (Python / PyO3 side).

Loads ``tests/parity/fixtures/derived-bundle-v1.json`` (generated by
``tests/parity/fixtures/generate-derived-bundle-v1.ts`` via the WASM binding)
and asserts that ``totalreclaw_core.derive_bundle_from_mnemonic`` /
``parse_bundle_v1`` / ``validate_bundle_v1`` produce byte-identical output to
the Rust (canonical) and TypeScript/WASM implementations.

``provisioned_at`` is deliberately excluded from the byte-equality
assertions — it is wall-clock-stamped inside ``derive_bundle_from_mnemonic``
(matching the crate's existing ``prepare_fact`` precedent) and is
"informational only" per derived-bundle-v1.md §4.1.

The TypeScript-side parity check lives at
``tests/parity/derived-bundle-parity.test.ts``. Together with the Rust-native
tests in ``rust/totalreclaw-core/src/bundle.rs``, this forms the three-way
guard the design doc requires (P2-4).

Run with: ``cd python && python -m pytest tests/test_bundle_parity.py -v``

Requires a `totalreclaw_core` build that includes the bundle bindings (Option
E Phase 2, #581) — a stable-channel `totalreclaw-core` wheel predating this
work does not export `derive_bundle_from_mnemonic`. Build the local crate
into the active venv first: ``cd rust/totalreclaw-core && maturin develop
--release --features python-extension``.
"""
from __future__ import annotations

import json
from pathlib import Path

import pytest

totalreclaw_core = pytest.importorskip("totalreclaw_core")

FIXTURE_PATH = (
    Path(__file__).resolve().parents[2] / "tests" / "parity" / "fixtures" / "derived-bundle-v1.json"
)


def _has_bundle_bindings() -> bool:
    return hasattr(totalreclaw_core, "derive_bundle_from_mnemonic")


pytestmark = pytest.mark.skipif(
    not _has_bundle_bindings(),
    reason="installed totalreclaw_core predates the derived-bundle-v1 bindings (#581)",
)


@pytest.fixture(scope="module")
def fixture() -> dict:
    if not FIXTURE_PATH.exists():
        pytest.skip(f"parity fixture not generated yet: {FIXTURE_PATH}")
    return json.loads(FIXTURE_PATH.read_text())


@pytest.fixture(scope="module")
def derived_json(fixture: dict) -> str:
    inputs = fixture["inputs"]
    return totalreclaw_core.derive_bundle_from_mnemonic(
        inputs["mnemonic"],
        inputs["chain_id"],
        inputs["provisioned_by"],
        inputs["smart_account"],
    )


def test_derive_bundle_from_mnemonic_matches_fixture_vault(fixture, derived_json):
    derived = json.loads(derived_json)
    expected_vault = fixture["expected"]["vault"]
    assert derived["vault"] == expected_vault


def test_derive_bundle_from_mnemonic_matches_fixture_signing(fixture, derived_json):
    derived = json.loads(derived_json)
    assert derived["signing"] == fixture["expected"]["signing"]


def test_derive_bundle_from_mnemonic_matches_fixture_account(fixture, derived_json):
    derived = json.loads(derived_json)
    assert derived["account"] == fixture["expected"]["account"]


def test_derive_bundle_from_mnemonic_matches_fixture_provisioned_by(fixture, derived_json):
    derived = json.loads(derived_json)
    assert derived["provisioned_by"] == fixture["expected"]["provisioned_by"]


def test_derive_bundle_from_mnemonic_version_and_schema(derived_json):
    derived = json.loads(derived_json)
    assert derived["version"] == 2
    assert derived["schema"] == "derived-bundle-v1"


def test_derive_bundle_from_mnemonic_provisioned_at_is_a_timestamp(derived_json):
    import datetime

    derived = json.loads(derived_json)
    # Must parse as an RFC 3339 / ISO 8601 timestamp; exact value is not
    # asserted (wall-clock, non-deterministic across runs).
    datetime.datetime.fromisoformat(derived["provisioned_at"].replace("Z", "+00:00"))


def test_derive_bundle_never_contains_the_mnemonic(fixture, derived_json):
    assert "abandon" not in derived_json


def test_parse_bundle_v1_returns_bytes_for_key_material(fixture, derived_json):
    parsed = totalreclaw_core.parse_bundle_v1(derived_json)

    assert isinstance(parsed["vault"]["encryption_key"], bytes)
    assert isinstance(parsed["vault"]["dedup_key"], bytes)
    assert isinstance(parsed["vault"]["auth_key"], bytes)
    assert isinstance(parsed["vault"]["lsh_seed"], bytes)
    assert isinstance(parsed["signing"]["private_key"], bytes)

    expected_vault = fixture["expected"]["vault"]
    assert parsed["vault"]["encryption_key"].hex() == expected_vault["encryption_key"]
    assert parsed["vault"]["dedup_key"].hex() == expected_vault["dedup_key"]
    assert parsed["vault"]["auth_key"].hex() == expected_vault["auth_key"]
    assert parsed["vault"]["lsh_seed"].hex() == expected_vault["lsh_seed"]


def test_parse_bundle_v1_signing_fields(fixture, derived_json):
    parsed = totalreclaw_core.parse_bundle_v1(derived_json)
    expected_signing = fixture["expected"]["signing"]
    assert parsed["signing"]["kind"] == expected_signing["kind"]
    assert parsed["signing"]["address"] == expected_signing["address"]
    assert parsed["signing"]["private_key"].hex() == expected_signing["private_key"]
    assert parsed["signing"]["grant"] is None  # owner-eoa carries no grant


def test_parse_bundle_v1_account_fields(fixture, derived_json):
    parsed = totalreclaw_core.parse_bundle_v1(derived_json)
    assert parsed["account"] == fixture["expected"]["account"]


def test_validate_bundle_v1_accepts_valid_bundle(derived_json):
    totalreclaw_core.validate_bundle_v1(derived_json)  # must not raise


def test_validate_bundle_v1_rejects_wrong_version(derived_json):
    bad = derived_json.replace('"version":2', '"version":3', 1)
    assert bad != derived_json
    with pytest.raises(ValueError):
        totalreclaw_core.validate_bundle_v1(bad)


def test_validate_bundle_v1_rejects_wrong_schema(derived_json):
    bad = derived_json.replace("derived-bundle-v1", "derived-bundle-v2", 1)
    assert bad != derived_json
    with pytest.raises(ValueError):
        totalreclaw_core.validate_bundle_v1(bad)


def test_validate_bundle_v1_rejects_address_private_key_mismatch(fixture, derived_json):
    bad = derived_json.replace(
        fixture["expected"]["signing"]["address"],
        "0x000000000000000000000000000000000000dd",
        1,
    )
    assert bad != derived_json
    with pytest.raises(ValueError):
        totalreclaw_core.validate_bundle_v1(bad)


def test_validate_bundle_v1_rejects_unknown_signing_kind(derived_json):
    bad = derived_json.replace('"kind":"owner-eoa"', '"kind":"root-eoa"', 1)
    assert bad != derived_json
    with pytest.raises(ValueError):
        totalreclaw_core.validate_bundle_v1(bad)


def test_validate_bundle_v1_rejects_malformed_json():
    with pytest.raises(ValueError):
        totalreclaw_core.validate_bundle_v1("not json")


def test_parse_bundle_v1_roundtrip_is_stable(fixture, derived_json):
    """Re-deriving with the same inputs must reproduce the same
    (non-timestamp) fields — proves determinism given identical inputs."""
    inputs = fixture["inputs"]
    again = totalreclaw_core.derive_bundle_from_mnemonic(
        inputs["mnemonic"],
        inputs["chain_id"],
        inputs["provisioned_by"],
        inputs["smart_account"],
    )
    d1 = json.loads(derived_json)
    d2 = json.loads(again)
    assert d1["vault"] == d2["vault"]
    assert d1["signing"] == d2["signing"]
    assert d1["account"] == d2["account"]
